service: my-serverless-app

provider:
    name: aws
    runtime: nodejs12.x
    memorySize: 128
    timeout: 10
    stage: production
    region: eu-central-1

functions:
    api:
        handler: lambda.universal
        events:
            - http: GET /lobby
            - http: POST /lobby
            - http: GET /lobby/players
            - http: PUT /lobby/players
